FIXHUB/Models/Technician.cs
using System;
using System.Collections.Generic;

namespace FIXHUB.Models;

public partial class Technician
{
    public int TechnicianId { get; set; }

    public int? UserId { get; set; }

    public string? Expertise { get; set; }

    public double? Rating { get; set; }

    public virtual ICollection<RequestAssignment> RequestAssignments { get; set; } = new List<RequestAssignment>();

    public virtual User? User { get; set; }
}

FIXHUB/Areas/Admin/Controllers/TechnicianController.cs
using FIXHUB.Areas.Admin.ViewModel;
using FIXHUB.Models;
using Microsoft.AspNetCore.Mvc;

namespace FIXHUB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TechnicianController : Controller
    {
        private readonly FixHubDbContext _context;
        public TechnicianController(FixHubDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var tech = (from t in _context.Technicians
                        join u in _context.Users on t.UserId equals u.UserId
                        join up in _context.UserProfiles on u.UserId equals up.UserId
                        select new
                        {
                            t.TechnicianId,
                            t.UserId,
                            t.Expertise,
                            t.Rating,
                            UserName = u.UserName,
                            ProfilePicture = up.AvatarUrl,
                            IsActive = u.IsActive
                        } 
                        
                        
                        ).ToList();
           var techVM = tech.Select(t => new TechnicianVM
           {
               TechnicianID = t.TechnicianId,
               UserID = t.UserId,
               Expertise = t.Expertise,
               Rating = t.Rating,
               UserName = t.UserName,
               ProfilePicture = t.ProfilePicture,
                IsActive = t.IsActive ?? true // Default to true if IsActive is null
           }).ToList();
            return View(techVM);
        }
    }
}

FIXHUB/Areas/Admin/Views/Technician/Index.cshtml
@using FIXHUB.ViewModels;
@model IList<TechnicianVM>



<h1>Danh sách kĩ thuât viên FIXHUB</h1>
<!-- Table Start -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">

        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">
                    <a type="button" class="btn btn-primary m-2" asp-area="Admin" asp-controller="Technician" asp-action="Create">
                        <i class="bi bi-plus-circle"></i>
                        Thêm mới
                    </a>
                </h6>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Tiêu đề</th>
                                <th scope="col">Ảnh</th>
                                <th scope="col">Tóm tắt</th>
                                <th scope="col">Ẩn/Hiện</th>
                                <th scope="col">Hành động</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var tech in Model)
                            {
                                <tr>
                                    <th scope="row">@tech.UserId</th>
                                    <td>@tech.UserName</td>
                                    <td>
                                        <img src="@tech.AvatarUrl" style="width:50px;height:50px" />
                                    </td>
                                    <td>@tech.Bio</td>
                                    <td>@tech.Expertise</td>
                                    <td>@tech.Rating</td>                              
                                    <td>
                                        <a asp-area="Admin" asp-controller="Technician" asp-action="Edit" asp-route-id="@tech.UserId" class="btn btn-warning m-2"><i class="bi bi-pencil-fill"></i>Sửa </a>
                                        <a asp-area="Admin" asp-controller="Technician" asp-action="Remove" asp-route-id="@tech.UserId" class="btn btn-danger m-2"><i class="bi bi-eraser-fill"></i>Xoá</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Table End -->